// ---------------------------------------------------------------- //
// This file is autogenerated by pioasm version 2.3.0; do not edit! //
// ---------------------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

#ifdef __cpp_constexpr
#define __pio_const constexpr
#else
#define __pio_const const
#endif

// --- //
// owi //
// --- //

#define owi_wrap_target 8
#define owi_wrap 16
#define owi_pio_version 1

#define owi_offset_reset_bus 0u
#define owi_offset_fetch_bit 8u

static __pio_const uint16_t owi_program_instructions[] = {
    0xff3c, //  0: set    x, 28           side 1 [15]
    0x1f41, //  1: jmp    x--, 1          side 1 [15]
    0xe628, //  2: set    x, 8            side 0 [6]
    0x0643, //  3: jmp    x--, 3          side 0 [6]
    0xa0c0, //  4: mov    isr, pins       side 0
    0x8020, //  5: push   block           side 0
    0xe738, //  6: set    x, 24           side 0 [7]
    0x0f47, //  7: jmp    x--, 7          side 0 [15]
            //     .wrap_target
    0x6021, //  8: out    x, 1            side 0
    0x152e, //  9: jmp    !x, 14          side 1 [5]
    0xe822, // 10: set    x, 2            side 0 [8]
    0x4401, // 11: in     pins, 1         side 0 [4]
    0x0f4c, // 12: jmp    x--, 12         side 0 [15]
    0x0008, // 13: jmp    8               side 0
    0xf522, // 14: set    x, 2            side 1 [5]
    0x1f4f, // 15: jmp    x--, 15         side 1 [15]
    0x4861, // 16: in     null, 1         side 0 [8]
            //     .wrap
};

#if !PICO_NO_HARDWARE
static __pio_const struct pio_program owi_program = {
    .instructions = owi_program_instructions,
    .length = 17,
    .origin = -1,
    .pio_version = owi_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config owi_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + owi_wrap_target, offset + owi_wrap);
    sm_config_set_sideset(&c, 1, false, true);
    return c;
}

#include <hardware/clocks.h>
static inline void owi_sm_init(PIO pio, uint sm, uint offset, uint pin_num, uint bits_per_word) {
    pio_sm_config c = owi_program_get_default_config(offset);
    sm_config_set_in_shift(
        &c,
        true,           // shift direction: right
        true,           // autopush: enabled
        bits_per_word   // autopush threshold
    );
    sm_config_set_out_shift(
        &c,
        true,           // shift direction: right
        true,           // autopull: enabled
        bits_per_word   // autopull threshold
    );
    sm_config_set_in_pins(&c, pin_num);
    sm_config_set_sideset_pins(&c, pin_num);
    float div = clock_get_hz(clk_sys) * 1e-6;
    sm_config_set_clkdiv(&c, div);
    pio_sm_init(pio, sm, offset + owi_offset_fetch_bit, &c);
    pio_sm_set_enabled(pio, sm, true);
}
static inline uint owi_reset_instr(uint offset) {
    return pio_encode_jmp(offset + owi_offset_reset_bus) | pio_encode_sideset(1, 0);
}

#endif

